### Create a new user 
POST http://localhost:3003/auth/signin
content-type: application/json

{
    "email": "mohitpal22@gmail.com",
    "password": "12345"
}


### SignUp a new user
POST http://localhost:3003/auth/signup
content-type: application/json

{
    "email": "mohitpal1112@gmail.com",
    "password": "12345"
}

### SignIn a existing user
POST http://localhost:3003/auth/signin
content-type: application/json

{
    "email": "mohitpal1112@gmail.com",
    "password": "12345"
}

### who am i
GET http://localhost:3003/auth/whoami

### SignOut a user
POST http://localhost:3003/auth/signout

### Find a particular user with a given ID
GET http://localhost:3009/auth/14

### Find all the users with given email
GET http://localhost:3009/auth?email=mk@gmail.com

### Delete a user with given ID
DELETE http://localhost:3009/auth/11

### Update a user with given ID
PATCH http://localhost:3009/auth/12
content-type: application/json

{
    "email": "abc@xyz.com",
    "password": "abcxyz"
}

### set cookie session 
GET http://localhost:3003/auth/colors/red

### get cookie session
GET http://localhost:3003/auth/colors